### ISSUE TITLE
Compression artifacts on lossy settings

### ISSUE THREAD

**Issue by RiccardoGiubilato** [TheRealOrange/icer_compression#8]
Amazing effort implementing this algorithm and leaving this to the community, thanks a lot for that!!
While playing with the algorithm I find that, while the lossless output works totally fine, the lossy outputs lead to artifacts in specific parts of the images. This happens on images characterized by strong spatial derivatives, e.g. sharp BW pictures. 
An example is attached here below: 

(diff image)
![trees_diff](https://github.com/user-attachments/assets/36d6a45a-755e-4b7a-a866-8fae21c172fc)

(icer compressed) 
![trees_icer](https://github.com/user-attachments/assets/9c5fbf8b-4386-4880-83cc-5d1eee2dc948)

(original)
![trees](https://github.com/user-attachments/assets/d2389abe-a303-4c11-b976-52a33732b0bf)

To produce this, I forced a byte quota of 100e3 bytes, on an input of 1024x1024 pixels. I used 4 stages, filter A, and 8 segments. While varying these parameters, especially the filter type, the distribution of artifacts changes but remains somewhere. 
I pre-processed the image converting the type to 16 bits first, so that the wavelet should not cause overflow, and then processed the data with the `icer_compress_image_uint16` / `icer_decompress_image_uint16` functions.

Would you have any idea where to look for potential issues / implementation errors?

**Comment by ephemeridis** [comment]
I have since fixed the issue. The artifacts are due to the wavelet stage treating the image plane (which is unsigned) as a signed integer (which is intended because the wavelet transform produces an expanded dynamic range output).

This is only visible on lossy compression because in case of an imperfect inverse wavelet transform, the dynamic range of the image does not return to the original, and there are negative values in the output image, which when interpreted as unsigned result in the white artifacting.

The fix I have applied is to clip negative values to zero.
